### ISSUE TITLE
EndpointException when trying to create new release. Malformed JSON/Wrong endpoint?

### ISSUE THREAD

**Issue by Andre601** [masecla22/Modrinth4J#9]
I'm getting the below exception when trying to create a new release for my project. Given the Exception name, I assume the endpoint is no longer accurate?

The code used:
https://codeberg.org/Andre601/AdvancedServerList/src/branch/master/version-uploader/src/main/java/ch/andre601/advancedserverlist/versionuploader/modrinth/ModrinthVersionUploader.java

GitHub Mirror should codeberg have loading issues:
https://github.com/Andre601/AdvancedServerList/blob/master/version-uploader/src/main/java/ch/andre601/advancedserverlist/versionuploader/modrinth/ModrinthVersionUploader.java

```
[ 20.09.2023 22:48:03 WARN  ] [ForkJoinPool.commonPool-worker-1] [ModrinthVersionUploader] - Encountered an exception while uploading a new release to Modrinth! 
java.util.concurrent.CompletionException: EndpointException(error=invalid_input, description=Error while parsing JSON: Base62 decoding overflowed at line 1 column 1379)
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1810)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: masecla.modrinth4j.exception.EndpointException: null
	at masecla.modrinth4j.endpoints.generic.Endpoint.checkBodyForErrors(Endpoint.java:176)
	at masecla.modrinth4j.endpoints.version.CreateVersion.lambda$sendRequest$0(CreateVersion.java:174)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 8 common frames omitted
```

**Comment by masecla22** [comment]
Issue seems to be with one of your parameters. You can ask in the Modrinth discord to see what is going wrong!

**Comment by Andre601** [comment]
Not sure how Modrinth would be able here to help... After all is this not a library they maintain, so there is no reason for them to help...

**Comment by Andre601** [comment]
Got a reply:
> That would mean you tried requesting an ID that overflows the base62 limit

Not sure what ID is meant here... Project ID? Version ID?

**Comment by masecla22** [comment]
Could you show me the project you are trying to work with on Modrinth?

**Comment by Andre601** [comment]
https://modrinth.com/plugin/advancedserverlist

**Comment by masecla22** [comment]
That's weird, the ID seems to match, specifically "xss83sOY" doesn't seem to be overflowing. 
I'm unsure what could be causing this, and eitherway the error doesn't make sense. Could you ask the Modrinth people about this ID in particular? I've been using this exact endpoint without any issues.

**Comment by Andre601** [comment]
A user on the discord brought up some ideas. What if the issue could be caused by either the version ID returned or one of the Dependency's IDs in the array?

**Comment by Andre601** [comment]
The issue was found!

The problem was that I provided the loader names with uppercase letters which labrinth apparently doesn't like.

So maybe have Modrinth4J sanitize these loaders by lowercasing them?
